FROM golang:latest as build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /api-bin ./cmd/api
 
FROM scratch

COPY --from=build /api-bin /api-bin

CMD ["/api-bin"]