FROM golang:latest as build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /worker-bin ./cmd/worker
 
FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=build /worker-bin /worker-bin
COPY config.yaml /config.yaml

CMD ["/worker-bin"]