FROM golang:latest as build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /worker-bin ./cmd/worker
 
FROM scratch

COPY --from=build /worker-bin /worker-bin

CMD ["/worker-bin"]